version: '3.8'

services:
  playwright-server:
    image: mcr.microsoft.com/playwright:v1.42.0-jammy
    container_name: playwright-chrome
    ports:
      - "9222:9222"
    command: >
      bash -c "
        cd /app && 
        npm config set strict-ssl false &&
        NODE_TLS_REJECT_UNAUTHORIZED=0 npx playwright@1.42.0 install chromium &&
        NODE_TLS_REJECT_UNAUTHORIZED=0 npx playwright@1.42.0 run-server --port=9222 --host=0.0.0.0
      "
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    shm_size: '2gb'
    volumes:
      - ./screenshots:/app/screenshots
      - ./.npmrc:/root/.npmrc
    restart: unless-stopped

networks:
  default:
    name: playwright-network
    driver: bridge 