version: '3.8'

services:
  playwright-server:
    # Use the pre-built image from Docker Hub
    image: sahajamit/playwright-chromium-server:latest
    container_name: playwright-chromium
    ports:
      - "9222:9222"
    shm_size: '2gb'
    volumes:
      - ./screenshots:/app/screenshots
    restart: unless-stopped

networks:
  default:
    name: playwright-network
    driver: bridge 