version: '3.8'

services:
  playwright-server:
    image: mcr.microsoft.com/playwright:v1.42.0-jammy
    container_name: playwright-chrome
    ports:
      - "9222:9222"
    command: >
      bash -c "
        cd /app && 
        npx playwright@1.42.0 install chromium &&
        npx playwright@1.42.0 run-server --port=9222 --host=0.0.0.0
      "
    shm_size: '2gb'
    volumes:
      - ./screenshots:/app/screenshots
    restart: unless-stopped

networks:
  default:
    name: playwright-network
    driver: bridge 